name: universal_ble_example
description: Demonstrates how to use the universal_ble plugin.
version: 2.0.0+11
publish_to: "none"

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  convert: ^3.1.1
  expandable: ^5.0.1
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.0
  device_info_plus: ^11.0.0
  universal_ble:
    path: ../
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.3.0
  shared_preferences: ^2.1.0
  package_info_plus: ^8.1.2
  provider: ^6.1.2
  file_picker: ^9.0.0
  protobuf: ^3.1.0
  tuple: ^2.0.2
  mobile_scanner: ^6.0.6
  


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path_provider: ^2.1.4
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  
  

flutter_native_splash:
  color: "#42a5f5" # Background color
  image: assets/splash.png # Splash image
  android: true # Enable Android support
  ios: true # Enable iOS support
  web: true # Enable web support

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/about_logo.png
    - assets/EMBP01.png
    - assets/EMBC22.png
